#!/usr/bin/env python3
# ============================================================
# Auto-generated by the GameDSL compiler. Do not edit by hand.
# ============================================================
import random
from runtime import (
    GameState, Player, MonsterType, Ability, Obstacle, run_game
)

entity_registry  = {}
ability_registry = {}
monster_registry = {}
game_state = GameState()


# ---- pre-statements (vars/fns declared before world) ----

# ---- world ----
GRID_WIDTH  = 50
GRID_HEIGHT = 50
DURATION    = 600

# ---- abilities ----
def _compute_Fireball_fields():
    fields = {}
    fields["damage"] = 25
    fields["range"] = 10
    fields["shape"] = "directional"
    fields["key"] = "space"
    return fields

ability_registry["Fireball"] = Ability("Fireball", type="active", img=None, **_compute_Fireball_fields())

# ---- monsters ----
monster_registry["Goblin"] = MonsterType("Goblin", health=30, img=None, movement="towards:Mage", count=5, position=(10, 10))

# ---- players ----
players = [
    Player("Mage", health=80, img=None, active=True, position=None, controls={"up": "w", "down": "s", "left": "a", "right": "d"})
]

# ---- obstacles ----
obstacles = []
obstacles.append(Obstacle("Wall", 20, 20, 5, 1, img=None))

# ---- assign abilities ----
game_state.assign_abilities("Mage", ["Fireball"])

# ---- win condition ----
def check_win_condition():
    return ((MonsterCount == 0) and (not (PlayerHealth < 10)))

# ---- post-statements (runtime game logic) ----

if __name__ == "__main__":
    run_game(players, monster_registry, obstacles, check_win_condition, GRID_WIDTH, GRID_HEIGHT, DURATION)
