#!/usr/bin/env python3
# ============================================================
# Auto-generated by the GameDSL compiler. Do not edit by hand.
# ============================================================
import random
from runtime import (
    GameState, Player, MonsterType, Ability, Obstacle, run_game,
    ability_registry
)

entity_registry  = {}
monster_registry = {}
game_state = GameState()

# ---- pre-statements (vars/fns declared before world) ----

# ---- world ----
GRID_WIDTH  = 25
GRID_HEIGHT = 20
DURATION    = 90

# ---- abilities ----
def _compute_Sword_fields():
    fields = {}
    fields["key"] = "SPACE"
    fields["damage"] = 25
    fields["range"] = 2
    fields["shape"] = "manhattan"
    return fields

ability_registry["Sword"] = Ability("Sword", type="active", img=None, **_compute_Sword_fields())
entity_registry["Sword"] = ability_registry["Sword"]

# ---- monsters ----
def _movement_Guard(self):
    while True:
        self.move(1, 0)
        self.move(1, 0)
        self.move(1, 0)
        game_state.wait(1)
        self.move(-1, 0)
        self.move(-1, 0)
        self.move(-1, 0)
        game_state.wait(1)

monster_registry["Guard"] = MonsterType("Guard", health=80, img=None, movement=_movement_Guard, count=2, position=None)
entity_registry["Guard"] = monster_registry["Guard"]

# ---- players ----
players = [
    Player("P1", health=100, img=None, active=True, position=(0, 0), controls={"up": "W", "down": "S", "left": "A", "right": "D"})
]
entity_registry["P1"] = players[0]

# ---- obstacles ----
obstacles = []
obstacles.append(Obstacle("HWall", 0, 10, 25, 1, img="assets/wall.png"))
obstacles.append(Obstacle("Pillar1", 5, 5, 1, 1, img=None))
obstacles.append(Obstacle("Pillar2", 5, 15, 1, 1, img=None))
obstacles.append(Obstacle("Pillar3", 20, 5, 1, 3, img=None))

# ---- assign abilities ----
game_state.assign_abilities("P1", ["Sword"])

# ---- win condition ----
def check_win_condition():
    return game_state.time_elapsed >= 90

# ---- post-statements (runtime game logic) ----

if __name__ == "__main__":
    run_game(players, monster_registry, obstacles, check_win_condition, GRID_WIDTH, GRID_HEIGHT, DURATION, game_state=game_state)
