#!/usr/bin/env python3
# ============================================================
# Auto-generated by the GameDSL compiler. Do not edit by hand.
# ============================================================
import random
from runtime import (
    GameState, Player, MonsterType, Ability, Obstacle, run_game,
    ability_registry
)

entity_registry  = {}
monster_registry = {}
game_state = GameState()

# ---- pre-statements (vars/fns declared before world) ----

# ---- world ----
GRID_WIDTH  = 20
GRID_HEIGHT = 15
DURATION    = 120

# ---- abilities ----
def _compute_Sword_fields():
    fields = {}
    fields["key"] = "SPACE"
    fields["damage"] = 30
    fields["range"] = 2
    fields["shape"] = "directional"
    fields["spread"] = 1
    return fields

ability_registry["Sword"] = Ability("Sword", type="active", img=None, **_compute_Sword_fields())
entity_registry["Sword"] = ability_registry["Sword"]

def _compute_Shield_fields():
    fields = {}
    fields["damage_reduction"] = 25
    fields["health_regen"] = 3
    return fields

ability_registry["Shield"] = Ability("Shield", type="permanent", img=None, **_compute_Shield_fields())
entity_registry["Shield"] = ability_registry["Shield"]

def _compute_Fireball_fields():
    fields = {}
    fields["key"] = "E"
    fields["damage"] = 50
    fields["range"] = 4
    fields["shape"] = "manhattan"
    fields["activates_at"] = 30
    return fields

ability_registry["Fireball"] = Ability("Fireball", type="timed", img=None, **_compute_Fireball_fields())
entity_registry["Fireball"] = ability_registry["Fireball"]

def _compute_Rage_fields():
    fields = {}
    fields["key"] = "Q"
    fields["required_kills"] = 5
    fields["damage_multiplier"] = 2
    return fields

ability_registry["Rage"] = Ability("Rage", type="kill_unlocked", img=None, **_compute_Rage_fields())
entity_registry["Rage"] = ability_registry["Rage"]

# ---- monsters ----
# ---- players ----
players = [
    Player("P1", health=100, img=None, active=True, position=(0, 0), controls={"up": "W", "down": "S", "left": "A", "right": "D"}),
    Player("P2", health=80, img=None, active=True, position=(19, 14), controls={"up": "UP", "down": "DOWN", "left": "LEFT", "right": "RIGHT"})
]
entity_registry["P1"] = players[0]
entity_registry["P2"] = players[1]

# ---- obstacles ----
obstacles = []

# ---- assign abilities ----
game_state.assign_abilities("P1", ["Sword", "Shield"])
game_state.assign_abilities("P2", ["Fireball", "Rage"])

# ---- win condition ----
def check_win_condition():
    return (game_state.players_alive == 1)

# ---- post-statements (runtime game logic, run as a coroutine) ----
def _game_script():
    return

if __name__ == "__main__":
    run_game(players, monster_registry, obstacles, check_win_condition,      GRID_WIDTH, GRID_HEIGHT, DURATION, game_state=game_state, script=_game_script)
