#!/usr/bin/env python3
# ============================================================
# Auto-generated by the GameDSL compiler. Do not edit by hand.
# ============================================================
import random
from runtime import (
    GameState, Player, MonsterType, Ability, Obstacle, run_game,
    ability_registry
)

entity_registry  = {}
monster_registry = {}
game_state = GameState()

# ---- pre-statements (vars/fns declared before world) ----

# ---- world ----
GRID_WIDTH  = 20
GRID_HEIGHT = 20
DURATION    = 180

# ---- abilities ----
def _compute_Slash_fields():
    fields = {}
    fields["key"] = "SPACE"
    fields["damage"] = 25
    fields["range"] = 1
    fields["shape"] = "manhattan"
    return fields

ability_registry["Slash"] = Ability("Slash", type="active", img=None, **_compute_Slash_fields())
entity_registry["Slash"] = ability_registry["Slash"]

def _compute_Bite_fields():
    fields = {}
    fields["key"] = "AUTO"
    fields["damage"] = 8
    fields["range"] = 1
    fields["shape"] = "manhattan"
    return fields

ability_registry["Bite"] = Ability("Bite", type="active", img=None, **_compute_Bite_fields())
entity_registry["Bite"] = ability_registry["Bite"]

# ---- monsters ----
monster_registry["Boss"] = MonsterType("Boss", health=500, img=None, movement="towards:P1", count=0, position=None)
entity_registry["Boss"] = monster_registry["Boss"]

monster_registry["Minion"] = MonsterType("Minion", health=30, img=None, movement="random", count=0, position=None)
entity_registry["Minion"] = monster_registry["Minion"]

# ---- players ----
players = [
    Player("P1", health=100, img=None, active=True, position=None, controls={"up": "W", "down": "S", "left": "A", "right": "D"}),
    Player("P2", health=100, img=None, active=False, position=None, controls={"up": "UP", "down": "DOWN", "left": "LEFT", "right": "RIGHT"})
]
entity_registry["P1"] = players[0]
entity_registry["P2"] = players[1]

# ---- obstacles ----
obstacles = []
obstacles.append(Obstacle("Wall", 8, 8, 4, 1, img=None))

# ---- assign abilities ----
game_state.assign_abilities("P1", ["Slash"])
game_state.assign_abilities("Boss", ["Bite"])
game_state.assign_abilities("Minion", ["Bite"])

# ---- win condition ----
def check_win_condition():
    return (game_state.monster_killed_count("Boss") >= 1)

# ---- post-statements (runtime game logic, run as a coroutine) ----
def _game_script():
    for _ in range(1):
        yield 10  # wait 10s
        game_state.spawn("P2", position=(19, 19))
    for _ in range(1):
        yield 30  # wait 30s
        game_state.spawn("Boss", position=(10, 10))
    while (game_state.time_elapsed < 180):
        yield 20  # wait 20s
        game_state.spawn("Minion")
        game_state.spawn("Minion")

if __name__ == "__main__":
    run_game(players, monster_registry, obstacles, check_win_condition,      GRID_WIDTH, GRID_HEIGHT, DURATION, game_state=game_state, script=_game_script)
