#!/usr/bin/env python3
# ============================================================
# Auto-generated by the GameDSL compiler. Do not edit by hand.
# ============================================================
import random
from runtime import (
    GameState, Player, MonsterType, Ability, Obstacle, run_game
)

entity_registry  = {}
ability_registry = {}
monster_registry = {}
game_state = GameState()


# ---- pre-statements (vars/fns declared before world) ----

# ---- world ----
GRID_WIDTH  = 10
GRID_HEIGHT = 10
DURATION    = 60

# ---- abilities ----
# ---- monsters ----
# ---- players ----
players = [
    Player("P1", health=100, img=None, active=True, position=None, controls={"up": "W", "down": "S", "left": "A", "right": "D"})
]

# ---- obstacles ----
obstacles = []

# ---- assign abilities ----

# ---- win condition ----
def check_win_condition():
    return game_state.time_elapsed >= 60

# ---- post-statements (runtime game logic) ----

if __name__ == "__main__":
    run_game(players, monster_registry, obstacles, check_win_condition, GRID_WIDTH, GRID_HEIGHT, DURATION)
