#!/usr/bin/env python3
# ============================================================
# Auto-generated by the GameDSL compiler. Do not edit by hand.
# ============================================================
import random
from runtime import (
    GameState, Player, MonsterType, Ability, Obstacle, run_game,
    ability_registry
)

entity_registry  = {}
monster_registry = {}
game_state = GameState()


# ---- pre-statements (vars/fns declared before world) ----
def scale_monster(name, amount):
    entity_registry[name].health = (entity_registry[name].health + amount)

def punish_on_death(target, boost):
    if (game_state.monster_count(target) == 0):
        entity_registry[target].health = boost

def boost_player_damage(pname, extra):
    entity_registry["Sword"].damage = (entity_registry["Sword"].damage + extra)


# ---- world ----
GRID_WIDTH  = 20
GRID_HEIGHT = 20
DURATION    = 150

# ---- abilities ----
def _compute_Sword_fields():
    fields = {}
    fields["key"] = "SPACE"
    fields["damage"] = 30
    fields["range"] = 2
    fields["shape"] = "directional"
    fields["spread"] = 1
    return fields

ability_registry["Sword"] = Ability("Sword", type="active", img=None, **_compute_Sword_fields())
entity_registry["Sword"] = ability_registry["Sword"]

def _compute_Bite_fields():
    fields = {}
    fields["key"] = "AUTO"
    fields["damage"] = 12
    fields["range"] = 1
    fields["shape"] = "manhattan"
    return fields

ability_registry["Bite"] = Ability("Bite", type="active", img=None, **_compute_Bite_fields())
entity_registry["Bite"] = ability_registry["Bite"]

# ---- monsters ----
monster_registry["Goblin"] = MonsterType("Goblin", health=60, img=None, movement="towards:P1", count=4, position=None)
entity_registry["Goblin"] = monster_registry["Goblin"]

monster_registry["Troll"] = MonsterType("Troll", health=150, img=None, movement="random", count=2, position=None)
entity_registry["Troll"] = monster_registry["Troll"]

# ---- players ----
players = [
    Player("P1", health=120, img=None, active=True, position=None, controls={"up": "W", "down": "S", "left": "A", "right": "D"})
]
entity_registry["P1"] = players[0]

# ---- obstacles ----
obstacles = []

# ---- assign abilities ----
game_state.assign_abilities("P1", ["Sword"])
game_state.assign_abilities("Goblin", ["Bite"])
game_state.assign_abilities("Troll", ["Bite"])

# ---- win condition ----
def check_win_condition():
    return (game_state.monster_killed_count("Goblin") >= 4)

# ---- post-statements (runtime game logic) ----
while (game_state.time_elapsed < 150):
    game_state.wait(30)
    scale_monster("Goblin", 10)
    scale_monster("Troll", 25)
    boost_player_damage("P1", 5)

if __name__ == "__main__":
    run_game(players, monster_registry, obstacles, check_win_condition, GRID_WIDTH, GRID_HEIGHT, DURATION)
