#!/usr/bin/env python3
# ============================================================
# Auto-generated by the GameDSL compiler. Do not edit by hand.
# ============================================================
import random
from runtime import (
    GameState, Player, MonsterType, Ability, Obstacle, run_game,
    ability_registry
)

entity_registry  = {}
monster_registry = {}
game_state = GameState()


# ---- pre-statements (vars/fns declared before world) ----
speed_mult = 1.5
dmg_base = 2.75
big_health = 9999
zero_count = 0

# ---- world ----
GRID_WIDTH  = 99
GRID_HEIGHT = 99
DURATION    = 999

# ---- abilities ----
def _compute_PowerUp_fields():
    fields = {}
    fields["damage_reduction"] = 99
    fields["damage_multiplier"] = speed_mult
    fields["health_regen"] = 10
    fields["speed_boost"] = 3
    return fields

ability_registry["PowerUp"] = Ability("PowerUp", type="permanent", img=None, **_compute_PowerUp_fields())

def _compute_NuclearStrike_fields():
    fields = {}
    fields["key"] = "E"
    fields["damage"] = 999
    fields["range"] = 9
    fields["shape"] = "chebyshev"
    fields["activates_at"] = 999
    return fields

ability_registry["NuclearStrike"] = Ability("NuclearStrike", type="timed", img=None, **_compute_NuclearStrike_fields())

def _compute_UltraRage_fields():
    fields = {}
    fields["key"] = "Q"
    fields["required_kills"] = 1
    fields["damage_multiplier"] = (dmg_base * 2)
    return fields

ability_registry["UltraRage"] = Ability("UltraRage", type="kill_unlocked", img=None, **_compute_UltraRage_fields())

# ---- monsters ----
monster_registry["Ghost"] = MonsterType("Ghost", health=1, img=None, movement="random", count=zero_count, position=None)

# ---- players ----
players = [
    Player("P1", health=big_health, img=None, active=True, position=None, controls={"up": "W", "down": "S", "left": "A", "right": "D"})
]

# ---- obstacles ----
obstacles = []
obstacles.append(Obstacle("BigWall", 0, 49, 99, 1, img=None))
obstacles.append(Obstacle("Dot", 50, 50, 1, 1, img=None))

# ---- assign abilities ----
game_state.assign_abilities("P1", ["PowerUp", "NuclearStrike", "UltraRage"])

# ---- win condition ----
def check_win_condition():
    return game_state.time_elapsed >= 999

# ---- post-statements (runtime game logic) ----

if __name__ == "__main__":
    run_game(players, monster_registry, obstacles, check_win_condition, GRID_WIDTH, GRID_HEIGHT, DURATION)
